<script type="text/javascript">//<![CDATA[
window.countries=[];countries['4']="Afghanistan";countries['1']="Egypt";countries['5']="Albania";
countries['6']="Algeria";countries['176']="Andorra";countries['7']="Angola";countries['244']="Anguilla";
countries['8']="Antigua and Barbuda";countries['2']="Equatorial Guinea";countries['9']="Argentina";
countries['225']="Armenia";countries['246']="Aruba";countries['226']="Azerbaijan";countries['3']="Ethiopia";
countries['10']="Australia";countries['11']="Bahamas";countries['12']="Bahrain";countries['13']="Bangladesh";countries['14']="Barbados";countries['15']="Belgium";countries['16']="Belize";countries['17']="Benin";countries['18']="Bermuda";countries['19']="Bhutan";countries['20']="Burma (Myanmar)";countries['21']="Bolivia";countries['228']="Bosnia-Herzegovina";countries['22']="Botswana";countries['23']="Brazil";countries['248']="British Virgin Islands";countries['24']="Brunei";countries['25']="Bulgaria";countries['26']="Burkina Faso";countries['27']="Burundi";countries['28']="Chile";countries['29']="People's Republic of China";countries['186']="Cook Islands";countries['31']="Costa Rica";countries['32']="Denmark";countries['33']="Germany";countries['34']="Dominica";countries['35']="Dominican Republic";countries['36']="Djibouti";countries['37']="Ecuador";countries['39']="El Salvador";countries['38']="Cote d'Ivoire (Ivory Coast)";countries['229']="Eritrea";countries['201']="Estonia";countries['40']="Falkland Islands";countries['41']="Fiji";countries['42']="Finland";countries['43']="France";countries['194']="French Guyana";countries['44']="Gabon";countries['45']="Gambia";countries['230']="Georgia";countries['46']="Ghana";countries['47']="Gibraltar";countries['48']="Grenada";countries['49']="Greece";countries['50']="United Kingdom";countries['175']="Guadeloupe";countries['51']="Guatemala";countries['52']="Guinea";countries['53']="Guinea-Bissau";countries['54']="Guyana";countries['55']="Haiti";countries['56']="Honduras";countries['57']="Hong Kong";countries['58']="India";countries['59']="Indonesia";countries['60']="Iraq";countries['61']="Iran";countries['62']="Ireland (Eire)";countries['63']="Iceland";countries['64']="Israel";countries['65']="Italy";countries['66']="Jamaica";countries['67']="Japan";countries['68']="Yemen";countries['70']="Jordan";countries['180']="Virgin Islands";countries['72']="Cayman Islands";countries['74']="Cambodia";countries['73']="Cameroon";countries['75']="Canada";countries['76']="Cape Verde";countries['231']="Kazakhstan";countries['77']="Qatar";countries['78']="Kenya";countries['232']="Kirgizstan";countries['233']="Kiribati";countries['79']="Colombia";countries['80']="Comoros";countries['81']="Congo";countries['199']="Croatia";
countries['84']="Cuba";countries['85']="Kuwait";countries['86']="Laos";countries['87']="Lesotho";countries['223']="Latvia";
countries['88']="Lebanon";countries['89']="Liberia";countries['90']="Libya";countries['173']="Liechtenstein";countries['234']="Lithuania";countries['91']="Luxembourg";countries['92']="Macau";countries['93']="Madagascar";countries['94']="Malawi";countries['95']="Malaysia";countries['96']="Maldives";countries['97']="Mali";countries['98']="Malta";countries['192']="Mariana Islands";countries['99']="Morocco";countries['235']="Marshall Islands";countries['174']="Martinique";countries['100']="Mauritania";countries['101']="Mauritius";countries['236']="Macedonia";countries['102']="Mexico";countries['237']="Moldova";
countries['177']="Monaco";countries['103']="Mongolia";countries['254']="Montenegro";countries['264']="Serbia";countries['245']="Montserrat";countries['104']="Mozambique";countries['195']="Namibia";countries['238']="Nauru";countries['105']="Nepal";countries['106']="New Caledonia";countries['107']="New Zeeland";countries['108']="Nicaragua";countries['110']="The Netherlands";countries['109']="Dutch Antilles";countries['111']="Niger";countries['112']="Nigeria";countries['82']="North Korea";countries['113']="Norway";countries['115']="Oman";countries['114']="Austria";countries['116']="Pakistan";countries['239']="Palau";countries['117']="Panama";countries['118']="Papua New Guinea";countries['119']="Paraguay";countries['120']="Peru";countries['121']="Philippines";countries['122']="Poland";countries['123']="Portugal";countries['178']="Puerto Rico";countries['193']="Reunion";countries['124']="Kinyarwanda";countries['125']="Romania";countries['202']="Russia";countries['126']="Solomon Islands";countries['127']="Zambia";countries['128']="Samoa";countries['171']="San Marino";countries['129']="Sao Tome and Principe";countries['130']="Saudi Arabia";countries['131']="Sweden";countries['132']="Switzerland";countries['133']="Senegal";countries['134']="Seychelles";countries['135']="Sierra Leone";countries['137']="Singapore";countries['200']="Slovakia";countries['198']="Slovenia";countries['138']="Somalia";countries['140']="Spain";countries['141']="Sri Lanka";countries['142']="St. Kitts and Nevis";countries['143']="St. Lucia";countries['144']="St. Vincent";countries['146']="South Africa";countries['145']="Sudan";countries['83']="South Korea";countries['147']="Surinam";countries['148']="Swaziland";countries['149']="Syria";countries['240']="Tajikistan";countries['170']="Tahiti";countries['30']="Taiwan";countries['150']="Tanzania";countries['151']="Thailand";countries['152']="Togo";countries['153']="Tonga";countries['154']="Trinidad and Tobago";countries['155']="Chad";
countries['156']="Czech Republic";countries['158']="Tunisia";countries['157']="Turkey";countries['241']="Turkmenistan";countries['247']="Turks and Caicos Islands";countries['242']="Tuvalu";countries['159']="Uganda";countries['197']="Ukraine";countries['160']="Hungary";countries['161']="Uruguay";countries['165']="United States of America";countries['224']="Uzbekistan";countries['191']="Vanuatu";countries['172']="Vatican City";
countries['163']="Venezuela";countries['164']="United Arab Emirates";countries['166']="Vietnam";countries['227']="Belarus";countries['167']="Zaire";countries['168']="Central African Republic";countries['136']="Zimbabwe";countries['169']="Cyprus";countries['276']="South Sudan";countries['277']="Kosovo";window.onloadSuggest=function(){if(typeof $=='undefined'){var $=function(string){return document.getElementById(string);}}
if($('destiny')!=null){addSuggestField("");initMMSuggest();}
return true;}
function initMMSuggest(){if(typeof $=='undefined'){var $=function(string){return document.getElementById(string);}}
var searchFormElement=$?$('searchForm'):false;if(searchFormElement&&searchFormElement.addEvent){searchFormElement.addEvent('submit',function(e){var data;if(window.mmSuggestSelectionTrackingData){data=s.pageName+';'+window.mmSuggestSelectionTrackingData;}else{data=s.pageName+';Matchmaker;No Choice;'}
var cookieKey='clickTracking';var doNothing=function(){};var readCookie=Cookie.read?Cookie.read:(Cookie.get?Cookie.get:doNothing);var writeCookie=Cookie.write?Cookie.write:(Cookie.set?Cookie.set:doNothing);deferredClickTrackingData=readCookie(cookieKey);var clickTrackingObj;if(deferredClickTrackingData!=null&&deferredClickTrackingData.length>0){clickTrackingObj=JSON.decode(deferredClickTrackingData);if(clickTrackingObj.prop28){clickTrackingObj.prop28=clickTrackingObj.prop28+','+data;}else{clickTrackingObj.prop28=data;}}else{clickTrackingObj={};clickTrackingObj.prop28=data;}
writeCookie(cookieKey,JSON.encode(clickTrackingObj));});}
var overObj=[$('start_stayPeriod'),$('end_stayPeriod'),$('singleRooms'),$('doubleRooms'),$('adults'),$('children'),$('perimeter'),$('age_0'),$('acc_0'),$('age_1'),$('acc_1'),$('age_2'),$('acc_2'),$('age_3'),$('acc_3'),$('age_4'),$('acc_4'),$('age_5'),$('acc_5'),$('rating')];SetupMMSuggest($('destiny'),{'requestURL':mmURLBase+"?max_results=25&Keywords=$v$&query=$v$&Language=en&Language_mode=exact&bias=100&TranslitName=$v$&Filter=0",'debug':false,'preFunction':function(target,rows){window.mmSuggestSelectionTrackingData=null;try{target.originalRows=rows;var root=new MMNode("","",target.value);window.hotelSearch_mmSuggestRoot=root;var sRows=rows;for(var z=0;z<sRows.length;z++){var cat=sRows[z][1];if(sRows[z][1]=='LOC')
cat="Location";if(sRows[z][1]=='POI')
cat="Point of interest";if(sRows[z][1]=="FPOI")
cat="Company location";if(sRows[z][1]=="REG")
cat="Region";if(sRows[z][1]=="IATA")
cat="IATA";if(sRows[z][1]=="DIST")
cat="District";var node=new MMNode(sRows[z][0],cat,sRows[z][0]);node.row=sRows[z];root.group(node);}
var result=[];if((target.parameters.flags&AS_NO_ROOT)==AS_NO_ROOT){root.levelUp();for(var i=0;i<root.children.length;i++){root.children[i].parent=null;}
root.getAsArray(result);result.shift();}else{root.getAsArray(result);}
return result;}catch(E){if(target.parameters.debug)
alert("groupedPreFunction error: "+E);}},'headerFunction':function(parent,rowArray){var result="<div class=\"mmheadline\" align=\"left\"><div>Choose a proposal or browse our locations.</div></div>";return result;},'footerFunction':function(parent,rowArray){var footer="<div class=\"suggFooter\"></div>";return footer;},'rowFunction':function(target,rowArray,field_index,row,iDiv){try{if(((target.parameters.flags&AS_DISPLAY_INPUT)==AS_DISPLAY_INPUT)&&(row==0)){var ih="<span class='suggInputHeader'><nobr>"+replaceHTMLEntities(rowArray[row][1])+" \""+replaceHTMLEntities(rowArray[row][0])+"\"</nobr></span>"
iDiv.innerHTML=ih;return false;}
var node=rowArray[row][2];var value=node.label;var cat=node.cat;var origrow=node.row;var iconSrc=target.parameters.iconPath+"ordner.gif";var ph=[];if(node.children.length==0){iconSrc=target.parameters.iconPath+"platzhalter.gif";}else if(node.parent!=null){ph.push("<");ph.push("img align='middle'");ph.push(" alt=''");ph.push(" src='");ph.push(target.parameters.iconPath);if(node.isLastChild()){ph.push("lastchild.gif");ph.push("'>");}else{ph.push("child.gif");ph.push("'>");}}
var parent=node;for(var i=node.level-1;i>0;i--){parent=parent.parent;var ph2=[];ph2.push("<");ph2.push("img align='middle'");ph2.push(" alt=''");ph2.push(" src='");ph2.push(target.parameters.iconPath);if(parent.isLastChild()){ph2.push("platzhalter.gif");ph2.push("'>");}else{ph2.push("line.gif");ph2.push("'>");}
ph=ph2.concat(ph);}
var result=true;var icon=[];icon.push("<");icon.push("img align='middle'");icon.push(" alt=''");icon.push(" src='");if(node.children.length>0){iconSrc=target.parameters.iconPath+"ordner.gif";icon.push(iconSrc);icon.push("'>");var iconText=icon.join('');var ih="<span class='suggGroupCaption'><nobr>"+ph.join('')+iconText+replaceHTMLEntities(rowArray[row][0])+"&nbsp;&nbsp;</nobr></span>";result=(target.parameters.flags&AS_GENERATED_CATEGORIES_NOT_SELECTABLE)!=AS_GENERATED_CATEGORIES_NOT_SELECTABLE;}else{icon.push(iconSrc);icon.push("'>");iconText=icon.join('');var ih="<span class='suggGroupProductOnly'><nobr>"+ph.join('')+iconText+replaceHTMLEntities(rowArray[row][0])+(origrow[2]!=''?'&nbsp;'+replaceHTMLEntities(origrow[2]):'')+(origrow[10]!=''&&countries[origrow[10]]!=null?'&nbsp;- '+replaceHTMLEntities(countries[origrow[10]]):'')+"</nobr></span>";}
iDiv.innerHTML=ih;return result;}catch(E){alert("mmGroupedRowFunction error: "+E);}},'overlappedObjects':overObj,'onActivate':function(input,row){var node=row[2];var realRow=node.row;if(realRow==null){realRow=[node.value];for(var i=1;i<input.originalRows[0].length;i++)
realRow.push("");}
if(realRow[1].match('POI')){addSuggestField('*'+realRow[6]);}else if(realRow[1].match('LOC')){addSuggestField('%'+realRow[6]);}else if(realRow[1].match('REG')){addSuggestField('%'+realRow[6]);}else if(realRow[1].match('FPOI')){addSuggestField('*'+realRow[6]);}else if(realRow[1].match('IATA')){addSuggestField('%'+realRow[6]);}else if(realRow[1].match('DIST')){addSuggestField('%'+realRow[6]);}else{alert('fehler: '+realRow[1]);}
var catPos=0;var totPos=0;var categories=window.hotelSearch_mmSuggestRoot.children;catLoop:for(var i=0;i<categories.length;i++){var itemsInCat=categories[i].children;for(var j=0;j<itemsInCat.length;j++){totPos++;if(itemsInCat[j]==row[2]){catPos=j+1;break catLoop;}}}
var category=realRow[1];window.mmSuggestSelectionTrackingData="Matchmaker;"+totPos+";"+category+":"+catPos;$('destiny').value=replaceEntity(realRow[0])+(realRow[2]!=''?' '+replaceEntity(realRow[2]):'');},'flags':AS_TABSELECTS+AS_NO_ROOT+AS_NOLOGO+AS_DISPLAY_INPUT+AS_GENERATED_CATEGORIES_NOT_SELECTABLE,'normalfg':'#000033','normalbg':'#ffffff','highlightfg':'#000033','highlightbg':'#b0b7bd','width':391,'inputTitle':"Proposals on your search for"})
if(Browser.ie8||Browser.ie7){setTimeout(function(){if(window.MooTools){var input=$($('destiny'));if(input&&typeof input==='object'){input.addEvent('keyup',triggerResize);}}},500);}else{if(window.MooTools){var input=$($('destiny'));if(input&&typeof input==='object'){input.addEvent('keyup',triggerResize);}}}}
function triggerResize(evt){if(window.mmOnResize&&typeof mmOnResize==='function'){$(evt.target).removeEvent('keyup',triggerResize);mmOnResize();}}
function replaceEntity(str){return str.replace(/&amp;/g,"&");}
function addSuggestField(value){if(typeof $=='undefined'){var $=function(string){return document.getElementById(string);}}
var tmpForm=$('destiny').form;var tmpFieldID="suggestedID";if(tmpForm.elements[tmpFieldID]==null){var hiddenField=document.createElement("input");hiddenField.setAttribute("type","hidden");hiddenField.setAttribute("name",tmpFieldID);hiddenField.setAttribute("id",tmpFieldID);hiddenField.setAttribute("value",value);tmpForm.appendChild(hiddenField);}else{tmpForm.elements[tmpFieldID].value=value;}}
//]]></script>




<script type="text/javascript">//<![CDATA[
var mmBase=window.location.protocol+"//"+window.location.hostname+((window.location.port!=null&&window.location.port!='')?":"+window.location.port:"")+"/hrs-suggest/";var mmURLBase=mmBase+"mmsuggest";var mmIconPath=mmBase+"images/";
//]]></script>
<script type="text/javascript" src="js/jquery/mmCompressedWide.js"></script>
<div class="tracking">
<script type="text/javascript">//<![CDATA[
display();
//]]></script>
<script language="JavaScript" type="text/javascript">var s_account="hotelrsglobal";window.s_trackingServer="";window.s_trackingServerSecure="";</script>
<script language="JavaScript" type="text/javascript" src="js/jquery/s_code.js"></script>
<script language="JavaScript" type="text/javascript">s.campaign="cid6011";s.channel="Public Web";s.eVar20="D=c26+\":\"+c25+\":\"+ch+\":\"+pageName";s.eVar23="D=s_vi";s.eVar45="cid6011";s.events="event14,event18,event55";s.linkTrackVars="channel,pagename,prop26";s.pageName="Homepage";s.products=";T6248,;T6296,;T6233";s.prop11="2014-05-22 13:36:59";s.prop18=";T6296;33,;T6233;4,;T6248;31";s.prop25="~6011~";s.prop26="en_US";s.prop27="D=ch+\":\"+pageName";s.prop32="D=c25+\":\"+ch+\":\"+pageName";s.prop33="No";s.prop48="cid6011:~6011~:Public Web:Homepage";s.prop51="D=\"~6011~:\"+ch+\":\"+pageName";s.prop52="2B80EA87D3A75D56A5B07FBC70F28D8F.60-2";s.prop55="~6011~";s.prop56="http:\/\/www.hrs.com\/web3\/jsp\/portal\/homepage.jsp?activity=initVisit";s.prop57="60-2";s.prop63="D=ch+\":\"+pageName";s.prop67="2014-05-22 13:36";s.prop71="-1";s.server="Web1000";s.formList="ratingForm,bookingProcessForm,contactForm,newsletterForm";s.rgvo=s.getValOnce('2B80EA87D3A75D56A5B07FBC70F28D8F.60-2','s_rgvo')?s.resetGetValOnce():false;</script>
<noscript><iframe name="KeepAlive" src="/web3/keepAlive.do;" marginwidth="1" marginheight="1" height="1" width="1" style="height:1px !important" border="0" frameborder="0"></iframe>
</noscript><script type="text/javascript">setTimeout(function(){initKeepAlive("/web3/keepAlive;jsessionid=2B80EA87D3A75D56A5B07FBC70F28D8F.60-2?clientId=ZW5fVVNfTkVYVA--&amp;cid=60-2",300*1000)},540*1000)</script>




<script type="text/javascript">//<![CDATA[
window.addEvent('domready',function(){var destination=$('destiny');if(!destination){var dlist=$$('.text.location');if(dlist.length==1){destination=dlist[0];}}
if(destination&&window.mmCallSearch){destination.oninput=function(){if(!destination.suggVisible){mmCallSearch(destination,10);}}}});
//]]></script>

<script type="text/javascript">//<![CDATA[
window.addEvent('domready',function(){window.setTimeout(function(){window.backgroundPageTrackingFinished=true;},1000);});
//]]></script>
<script type="text/javascript">//<![CDATA[
new Request({'url':"/web3/media;jsessionid=2B80EA87D3A75D56A5B07FBC70F28D8F.60-2?clientId=ZW5fVVNfTkVYVA--&amp;cid=60-2&mediaID=-1"}).get();
//]]></script>
